### ISSUE TITLE
Issue with pyqt < 5.12

### ISSUE THREAD

**Issue by ancabilloni** [Dennis-van-Gils/python-dvg-pyqtgraph-threadsafe#1]
I'm trying to install this on pyqt 5.9.2 (to work with fbs for packaging). And I got error below. 
Can you advice what I should do?
```
Collecting pyqt5~=5.12 (from dvg-pyqtgraph-threadsafe)
  Using cached https://files.pythonhosted.org/packages/1d/31/896dc3dfb6c81c70164019a6cbba6ab037e3af7653d9ca60ccc874ee4c27/PyQt5-5.15.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-topj9b3k/pyqt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-topj9b3k/pyqt5/
```

**Comment by Dennis-van-Gils** [comment]
Hi An. This issue falls outside of the scope of my pyqtgraph-threadsafe library. Note that you are trying to use pyqt 5.9.2, whereas the minimum requirement for this library is pyqt 5.12. Sorry, but I can't provide support for your case.

**Comment by Dennis-van-Gils** [comment]
I suggest that you try creating a separate python environment using pyqt 5.12 and see if you're able to run the included demo of this library. It would help you in narrowing down potential issues with your system.
